name: CI/CD for Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        # Build Docker image (replace with your actual build steps)

    - name: Run tests
      run: |
        # Run tests inside the Docker container (replace with your actual test commands)

    - name: Push Docker image
      run: |
        # Push the built image to your container registry

  


    
